food/urls.py
from django.urls import path
from rest_framework import routers
from .api import FoodItemViewSet, CartItemViewSet, CartView, OrderListView, PlaceOrder, success_response
# from .views import Home, failure, success

router = routers.DefaultRouter()

router.register('api/food', FoodItemViewSet, 'food-items')
# router.register('api/cart-items', CartItemViewSet, 'cart-items')

urlpatterns = [
    path('api/cart-items/', CartView.as_view(), name="cart-items"),
    path('api/my-orders', OrderListView.as_view(), name="my-orders"),   
    path('api/place_order', PlaceOrder.as_view()),
    path('api/payment/success', success_response),
    # path('api/payment/fail', failure ),
    ] + router.urls

foodLust/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('site-admin/', include('site-admin.urls')),
    path('api/', include('user.urls')),
    path('', TemplateView.as_view(template_name = 'index.html')),
    path('', include('food.urls')),
    # re_path('^.*/', TemplateView.as_view(template_name = 'index.html')),
    
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

site-admin/urls.py
from .views import all_orders_view, change_order_status, order_details, user_list, food_list_view, food_detail_view, food_create_view, food_update_view
from .delivery import deliveries_view
from django.contrib import admin, auth

from django.urls import path, include

urlpatterns = [    
    path('all-orders/', all_orders_view, name='all-orders'),
    path('change-order-status/', change_order_status, name='change-order-status'),
    path('order-details/<int:pk>', order_details, name="order-details"),
    path('deliveries/', deliveries_view, name='deliveries'),
    path('food-items/',food_list_view , name="admin-foodlist" ),
    path('food-items/<int:pk>/',food_detail_view , name="admin-foodlist"),  
    path('food-items/create/', food_create_view ,name="admin-food-create"),
    path('food-items/<int:pk>/update/', food_update_view ,name="admin-food-update"),
    path('users/', user_list, name="admin-userlist" )
]

user/urls.py
from django.urls import path, include
from .views import my_orders_view, order_details
from .api import RegisterAPI, LoginAPI, UserAPI
from knox import views as knox_views
urlpatterns = [
    path('auth/', include('knox.urls')),
    path('auth/register', RegisterAPI.as_view()),
    path('auth/login', LoginAPI.as_view()),
    path('auth/user', UserAPI.as_view()),
    path('my-orders/', my_orders_view, name="my-orders"),
    path('order-details/', order_details, name="order-details"),
]

food/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from user.models import SiteSettings
from payu.models import Transaction

foodCatergoryChoices = (
    ('GY', 'Gym Food'),
    ('BR', 'Breakfast')
)

# Create your models here.
class FoodItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField( blank=True, null=True)
    image = models.ImageField(blank= False, null =True, upload_to="food-images")
    price = models.DecimalField(max_digits=10, decimal_places =1)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True, blank=False, null=False)
    category = models.CharField(max_length=2, choices=foodCatergoryChoices, null=True)
    
    def __str__(self):
        return self.name


class CartItem(models.Model):
    item = models.ForeignKey(FoodItem, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveSmallIntegerField(default=1)
    def __str__(self):
        return self.item.name
    @property
    def total_cost(self):
        return self.quantity * self.item.price

payment_choices = (('C', 'Cash On Delivery'),
('P', 'Paytm'),
)

order_status_choices = (
    ('N', 'New'),
    ('C', 'Cooking'),
    ('W', 'Ready'),
    ('IT', 'In-transit'),
    ('D', 'Delivered'),
    ('CBU', 'Canceled by User'),
    ('CBA', 'Canceled by Admin')
)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(CartItem)
    created_at = models.DateTimeField(auto_now_add=True)
    placed_at = models.DateTimeField(null=True, blank=True)

    # AddressDetails

    address_line1 = models.CharField(max_length=500, blank=True, null=True)
    address_line2 = models.CharField(max_length=500, blank=True, null=True)
    pincode = models.CharField(max_length=8, blank=True, null=True)
    instructions = models.TextField(null=True, blank=True)
    
    paymentMethod = models.CharField(max_length=1, choices =payment_choices)
    payment = models.OneToOneField(Transaction,on_delete=models.SET_NULL,  blank=True, null = True)
    total = models.DecimalField(max_digits=10, decimal_places=1, blank=True, null=True)
    # mobile_no = models.numberField()

    status = models.CharField(max_length=3,blank=True, null=True, choices = order_status_choices)

    
    def order(self):
        self.total = self.get_total()
        self.placed_at = timezone.now()
        # breakpoint()
        self.ordered = True        
        self.status='N'
        self.save()

    def get_pretotal(self):
        pretotal =0
        for item in self.items.all() : 
            pretotal += item.item.price * item.quantity
        return pretotal


    def get_total(self):
        if self.ordered:
            return self.total
        else:
            total = self.get_pretotal()
            total += self.get_calculated_tax()
        return total

    def get_calculated_tax(self):
        pretotal = self.get_pretotal()
        site_settings = SiteSettings.objects.all().first()
        tax = site_settings.tax * pretotal / 100
        return tax
        
    @property
    def tax_percentage(self):
        site_settings = SiteSettings.objects.all().first()
        return site_settings.tax 


# class OrderAddress(models.Model):

site-admin/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class SiteSettings(models.Model):
    tax = models.PositiveIntegerField()

class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_delivery_guy = models.BooleanField(default=False)
    profile_picuture = models.ImageField(upload_to="user-profile")

site-admin/forms.py
from django import forms
from food.models import FoodItem

class FoodItemForm(forms.ModelForm):
    class Meta:
        model = FoodItem
        fields = "__all__"
        

site-admin/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, response
from django.contrib.auth.decorators import user_passes_test, login_required

# Create your views here. 
from .forms import FoodItemForm
from food.models import Order, FoodItem
from user.models import SiteSettings, UserProfile
from .delivery import is_delivery_guy

def all_orders_view(request):
    
    orders =  {
        'New' : Order.objects.filter(status='N'),
        'Cooking' : Order.objects.filter(status='C'),
        'Waiting for Pickup' : Order.objects.filter(status='W'),
        'In Transit' : Order.objects.filter(status='IT'),
        'Delivered' : Order.objects.filter(status='D'),
        'Canceled' : Order.objects.filter(status__in = ['CBU', 'CBA'])
    }

    context = { 
        'orders': orders,
        'all_orders' : Order.objects.all(),

    }
    return render(request, 'site-admin/all_orders.html', context)

def change_order_status(request):
    
    if request.is_ajax() or request.POST:
        order = Order.objects.filter(ordered=True, pk=request.POST['pk']).first()
        if request.user.is_superuser:
            order.status = request.POST['status']
            order.save()
            
        elif is_delivery_guy(request.user):
            if order.status in ["W", "IT"] :
                order.status = order.next_status()
                order.save()

    return redirect('all-orders')


@login_required()
def order_details(request, pk):

    order = get_object_or_404(Order, pk=pk)
    site_settings = SiteSettings.objects.all().first()
    context = {
        'order': order,
        'settings': site_settings
    }
    return render(request, 'site-admin/order_details.html' ,context)


def user_list(request):
    context = {
        'users' : User.objects.all(),
    }

    if request.method == "POST"  and request.user.is_superuser:
        pk = request.POST['user_pk']
        status = request.POST['status']
        user = get_object_or_404(User, pk= pk)
        user.is_superuser = False

        user_profile_qs = user.userprofile_set.all()
        if user_profile_qs.exists():
            user_profile = user_profile_qs.first()
            
        else:
            user_profile = UserProfile(user=user)
        user_profile.is_delivery_guy = False

        if status == 'admin':
            user.is_superuser = True
        elif status == 'delivery_guy':
            user_profile.is_delivery_guy = True
        
        user.save()
        user_profile.save()

    return render(request, 'site-admin/users.html', context )

def food_list_view(request):
    context = {
        "food_items": FoodItem.objects.all()
    }
    return render(request, 'site-admin/food-item-list.html',context)

def food_detail_view(request, pk):
    context = {
        "item": get_object_or_404(FoodItem, pk=pk)
    }
    return render(request, 'site-admin/food-item-detail.html',context)

def food_create_view(request):
    
    form = FoodItemForm()
    if request.POST :
        form = FoodItemForm(request.POST)
        if form.is_valid() :
            obj = form.save()
            return redirect('admin-foodlist', obj.pk)
    context = {
        "form": form
    }
    return render(request, 'site-admin/food-item-create.html',context)

def food_update_view(request, pk):
    instance = get_object_or_404(FoodItem, pk= pk)
    form = FoodItemForm(instance = instance)

    if request.POST :
        form = FoodItemForm(request.POST or None, request.FILES or None, instance = instance)
        if form.is_valid() :
            obj = form.save()
            return redirect('admin-foodlist', obj.pk)
    context = {
        "form": form, 
        "item" : instance,
    }
    return render(request, 'site-admin/food-item-create.html',context)

user/views.py
from django.shortcuts import render
from food.models import Order
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def my_orders_view(request):
    context = {
        'orders': Order.objects.filter(user = request.user, ordered= True).order_by("-placed_at")
    }
    return render(request, "users/my-orders.html", context)

@login_required()
def order_details(request, pk):

    order = get_object_or_404(Order, pk=pk)
    site_settings = SiteSettings.objects.all().first()
    context = {
        'order': order,
        'settings': site_settings
    }
    return render(request, 'user/order_details.html',context)

site-admin/templates/site-admin/all_orders.html
{%extends 'site-admin/base.html'%} {%load static%} {%block innerhead%}
<link rel="stylesheet" href="{%static 'css/site-admin/all_orders.css'%}" />
{%endblock%} {%block innercontent%}
<section class="all-orders-section">
  <div class="inner-wrapper">
    <h1>Orders</h1>
    <ul class="dashboard">
      {%for key, orderCategory in orders.items%}
      <li>
        <span>{{orderCategory|length}}</span>
        <p>{{key|lower}}</p>
      </li>
      {%endfor%}
    </ul>
  </div>
</section>
{%for key, orderCategory in orders.items%}
<section class="orders-list-section">
  <div class="inner-wrapper">
    <h1>
      {{key}}
    </h1>
    <div class="orders-grid">
      <div class="orders-grid-heading">
        <span>Order Details</span>
        <span>Instructions</span>
        <span>Actions</span>
      </div>
      {%if orderCategory %} {%for order in orderCategory%}
      <div class="order-list-item">
        <div>
          <p class="order-id">Order Id : <span>{{order.pk}}</span></p>
          <p class="view-details">
            <a href="{%url 'order-details' order.pk%}">View Details</a>
          </p>
          <p class="date">{{order.placed_at}}</p>
        </div>
        <ul>
          {%for item in order.items.all%}
          <li>{{item.item.name}} x{{item.quantity}}</li>
          {%endfor%}
        </ul>
        <div>
          <p>{{order.instructions}}</p>
        </div>
        <div>
          <p></p>
          <form
            class="OrderStatusForm"
            method="POST"
            action="{%url 'change-order-status'%}"
          >
            <input type="hidden" value="{{order.next_status}}" name="status" />
            <input type="hidden" value="{{order.pk}}" name="pk" />
            {%csrf_token%} {%if order.next_button_text%}
            <input
              class="btn"
              type="submit"
              value="{{order.next_button_text}}"
            />
            {%endif%}
          </form>
        </div>
      </div>
      {%endfor%} {%else%}
      <div class="order-item-none">
        No orders yet.
      </div>
      {%endif%}
    </div>
  </div>
</section>

{%endfor%}

<script>
    document.getElementById('all-orders-link').classList.add("active");
</script>
{%endblock%}

site-admin/templates/site-admin/base.html
{%extends 'base.html'%} 
{%load static%} 
{%block head%}
    <link rel="stylesheet" href="{%static 'css/site-admin/base.css'%}" />
    {%block innerhead%} {%endblock%}
{%endblock%}

{%block content%} 
<div class="admin-container">
    <div class="admin-dash-nav">
        <div class="admin-dash-nav-content">
            <h2>Admin Dashboard</h2>
            <ul>
                {% comment %} <li>Today</li> {% endcomment %}
                <a href="{%url 'all-orders'%}"><li id="all-orders-link">Orders</li></a>
                <a href="{%url 'admin-userlist'%}"><li id="users-link">Users</li></a>
                <a href="{%url 'admin-foodlist'%}"><li id="food-link">Food Items</li></a>
            </ul>
        </div>
    </div>
    
    <div class="admin-content">
        {%block innercontent%}{%endblock innercontent%}
    </div>
</div>
{%endblock%}

site-admin/templates/site-admin/delivery_dashboard.html
{%extends 'base.html'%} {%load static%} {%block head%}
<link rel="stylesheet" href="{%static 'css/all_orders.css'%}" />
{%endblock%} {%block content%}
<section class="all-orders-section">
  <div class="wrapper">
    <h1>Orders</h1>
    <ul class="dashboard">
      {%for key, orderCategory in orders.items%}
      <li>
        <span>{{orderCategory|length}}</span>
        <p>{{key|lower}}</p>
      </li>
      {%endfor%}
    </ul>
  </div>
</section>
{%for key, orderCategory in orders.items%}
<section class="orders-list-section">
  <div class="wrapper">
    <h1>
      {{key}}
    </h1>
    <div class="orders-grid">
      <div class="orders-grid-heading">
        <span>Order Details</span>
        <span>Instructions</span>
        <span>Actions</span>
      </div>
      {%if orderCategory %} {%for order in orderCategory%}
      <div class="order-list-item">
        <div>
          <p class="order-id">Order Id : <span>{{order.pk}}</span></p>
          <p class="view-details">
            <a href="{%url 'order-details' order.pk%}">View Details</a>
          </p>
          <p class="date">{{order.placed_at}}</p>
        </div>
        <ul>
          {%for item in order.items.all%}
          <li>{{item.item.name}} x{{item.quantity}}</li>
          {%endfor%}
        </ul>
        <div>
          <p>{{order.instructions}}</p>
        </div>
        <div>
          {%if key == 'Waiting for Pickup' or key == 'In Transit' %}
          <form
            class="OrderStatusForm"
            method="POST"
            action="{%url 'change-order-status'%}"
          >
            <input type="hidden" value="{{order.next_status}}" name="status" />
            <input type="hidden" value="{{order.pk}}" name="pk" />
            {%csrf_token%} {%if order.next_button_text%}
            <input
              class="btn"
              type="submit"
              value="{{order.next_button_text}}"
            />
            {%endif%}
          </form>
          {%endif%}
        </div>
      </div>
      {%endfor%} {%else%}
      <div class="order-item-none">
        No orders yet.
      </div>
      {%endif%}
    </div>
  </div>
</section>

{%endfor%}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{%endblock%}

site-admin/templates/site-admin/food-item-create.html
{%extends 'site-admin/base.html'%} 
{%load static%}
{%block innerhead%}
<link rel="stylesheet" href="{%static 'css/site-admin/food-item-create.css'%}" />
{%endblock%}
{%block innercontent%}

<section class="food-section">
  <div class="inner-wrapper">
    <a class="go-back" onClick="javascript:history.go(-1);">Go back</a>
    {%if item%}
        <h1>Edit : {{item.name}}</h1>
    {%else%}
        <h1>Create Food Item</h1>
    {%endif%}
    <div class="details-container">
        <form method="POST" class="detail-content">
            {{form.as_p}}
            {%csrf_token%}
            {% if item %}<input type="submit" value="Update"> {% else %} <input type="submit" value="Create">{% endif %}
        </form>

    </div>
  </div>
</section>
<script>
    document.getElementById('food-link').classList.add("active");
</script>
{%endblock%}

site-admin/templates/site-admin/food-item-detail.html
{%extends 'site-admin/base.html'%} 
{%load static%}
{%block innerhead%}
<link rel="stylesheet" href="{%static 'css/site-admin/food-item-detail.css'%}" />
{%endblock%}
{%block innercontent%}

<section class="food-section">
  <div class="inner-wrapper">
    <a class="go-back" onClick="javascript:history.go(-1);">Go back</a>
    <div class="title">
        <h1>{{item.name}}</h1>
        <a href="{% url 'admin-food-update' item.pk%}">Edit</a>
    </div>
    <div class="details-container">
        <div class="image">
            {%if item.image%}
            <img src="{{item.image.url}}">
            {%endif%}
        </div>
        <div class="detail-content">
            <p><span>Name:</span> {{item.name}}</p>
            <p><span>Description:</span>  {{item.description}}</p>
            <p><span>Price:</span>  ₹{{item.price}}</p>
            <p><span>Category:</span>  {{item.get_category_display}}</p>
            <p>
            {%if item.active %}
                <span class="status-active">Active</p>
            {%else%}
                <span class="status-inactive">Inactive</p>
            {%endif%}
            </p>
        </div>

    </div>
  </div>
</section>
<script>
    document.getElementById('food-link').classList.add("active");
</script>
{%endblock%}

site-admin/templates/site-admin/food-item-list.html
{%extends 'site-admin/base.html'%} 
{%load static%}
{%block innerhead%}
<link rel="stylesheet" href="{%static 'css/site-admin/food-item-list.css'%}" />
{%endblock%}
{%block innercontent%}

<section class="food-section">
    <div class="inner-wrapper">
    <div class="title">
        <h1>Food Items</h1>
        <a href="{% url 'admin-food-create' %}">Create a New Item</a>
    </div>

    <div class="itemlist">
        <div class="itemlist-header">
            <span>Item Name</span>
            <span>Category</span>
            <span>Price</span>
            <span>Status<span>
        </div>
        {%for item in food_items%}
        <form method="POST">
            <a href="{%url 'admin-foodlist' item.pk%}"><span>{{item.name}}</span></a>
            <span>{{item.get_category_display}}</span>
            <span>₹{{item.price}}</span>
            {%if item.active %}
            <span class="status-active">Active</span>
            {%else%}
            <span class="status-inactive">Inactive</span>
            {%endif%}
        </form>
        {%endfor%}
    </div>
  </div>
</section>
<script>
    document.getElementById('food-link').classList.add("active");
</script>
{%endblock%}

site-admin/templates/site-admin/order_details.html
{%extends 'base.html'%}
{%load static%}

{%block head%}
<link rel="stylesheet" href="{%static 'css/order_details.css'%}">
{%endblock%}

{%block content%}
<div class="wrapper">
    <a class="go-back" onClick="javascript:history.go(-1);">Go back</a>
    <h1>Order Id: {{order.pk}}</h1>
    <div class="tabs">
        <div class="order-box">
            <div class="user-details">
                <span>Name:</span><span>{{order.user.username}}</span>
                <span>Mobile no:</span><span>{{order.mobile}}</span>
                <span>Email:</span><span>{{order.user.email}}</span>
            </div>
            <div class="address">
                <span>Address line 1:</span><span>{{order.address_line1}}</span>
                <span>Address line 2:</span><span>{{order.address_line2}}</span>
                <span>Pincode:</span><span>{{order.pincode}}</span>
            </div>
            <div class="order-details">
                <span>Instructions: </span><span>{{order.instructions}}</span>
                <span>Status:</span><span>{{order.get_status_display}}</span>
                <span>Payment Mode:</span><span>{{order.get_paymentMethod_display}}</span>
            </div>
        </div>
        <aside>
            <div class="cart-summary">
                {%for item in order.items.all%}
                <div class="item"><span>{{item.item.name}}
                    <span class="highlight">X{{item.quantity}}</span></span>
                    <span class="price">₹{{item.total_cost}}</span>
                </div>
                {%endfor%}
                <div class="gst-item">
                    <span>GST @{{settings.tax}}%</span>
                    <span class="price">₹{{order.get_calculated_tax}}</span>
                </div>
                <div class="total-item">
                    <span>Total</span>
                    <span>₹{{order.get_total}}</span>
                </div>
            </div>
        </aside>
    </div>
    
</div>

{%endblock%}

site-admin/templates/site-admin/users.html
{%extends 'site-admin/base.html'%} 
{%load static%}
{%block innerhead%}
<link rel="stylesheet" href="{%static 'css/site-admin/users.css'%}" />
{%endblock%}
{%block innercontent%}

<section class="user-section">
  <div class="inner-wrapper">
    <h1>Users</h1>
    <form class="user-search">
        <input type="text" placeholder="Username, Email or Name" >
        <input type="submit" value= "Search"> 
    </form>
  
    <div class="userlist">
        <div class="userlist-header">
            <span>Username</span>
            <span>Email</span>
            <span>Name</span>
            <span>Status<span>
        </div>
        {%for user in users%}
        <form method="POST">
            <span>{{user.username}}</span>
            <span>{{user.email}}</span>
            <span>{{user.full_name}}</span>
            <div>
                {%csrf_token%}
                <input type="hidden" value="{{user.pk}}" name="user_pk">
                <select name="status">
                    <option value="regular_user">Regular User</option>
                    <option value="delivery_guy"  
                    {%if user.userprofile_set.all.first.is_delivery_guy%}selected{%endif%}>Delivery Guy</option>
                    <option value="admin" {%if user.is_superuser%}selected{%endif%}>Admin</option>
                </select>
                <input type="submit" value="Save">
            </div>
        </form>
        {%endfor%}
    </div>
  </div>
</section>
<script>
    document.getElementById('users-link').classList.add("active");
</script>
{%endblock%}